import = [
        "~/.config/alacritty/catppuccin-mocha.toml"
]
shell = { program = "/bin/zsh", args = ["-l"]}

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
opacity = 0.75

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
size = 10.5
glyph_offset = { x = 0, y = 0 }
