os:
    edit: "floatterm"

gui:
    theme:
        selectedLineBgColor:
            - underline
        selectedRangeBgColor:
            - underline

git:
    paging:
        colorArg: never
        pager: delta --paging=never
