os:
  editPreset: "nvim"
gui:
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
  nerdFontsVersion: "3"
git:
  pagers:
    - colorArg: never
      pager: delta --paging=never
