os:
    editPreset: "nvim"

gui:
    theme:
        selectedLineBgColor:
            - underline
        selectedRangeBgColor:
            - underline
    nerdFontsVersion: "3"

git:
    paging:
        colorArg: never
        pager: delta --paging=never
