os:
  editPreset: "nvim"
gui:
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
  nerdFontsVersion: "3"
git:
  diffRenderers:
    - colorArg: never
      command: delta --paging=never
